import { cn } from '@/lib/utils'
import './globals.css'
import { Raleway as FontSans } from 'next/font/google'
import { Header } from '@/components/layout/header'
import { ThemeProvider } from 'next-themes'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head></head>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ThemeProvider
          attribute="data-mode"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
