import { cn } from '@/lib/utils'
import './globals.css'
import { Raleway as FontSans } from 'next/font/google'
import { Header } from '@/components/layout/header'
import { ThemeProvider } from 'next-themes'
import { Footer } from '@/components/layout/footer'
import { Toaster } from '@/components/ui/sonner'
import { getPayloadHMR } from '@payloadcms/next/utilities'
import config from '@payload-config'
import { getCachedPayload } from '@/plugins/cachedPayload'
import { GLOBAL_SLUG } from '@/constants'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const payload = await getPayloadHMR({ config })
  const cachedPayload = getCachedPayload(payload)
  const settings = await cachedPayload.findGlobal({ slug: GLOBAL_SLUG.SETTINGS })
  const footerForm =
    typeof settings?.forms?.footerForm === 'object' ? settings?.forms?.footerForm : null

  return (
    <html lang="ru" suppressHydrationWarning>
      <head></head>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <ThemeProvider
          attribute="data-mode"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
